//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Control Interface App/ControllerScripts/GameController.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameController: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameController()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameController"",
    ""maps"": [
        {
            ""name"": ""DriveControl"",
            ""id"": ""e5e5d280-958e-44dc-b7ee-5e2d80762027"",
            ""actions"": [
                {
                    ""name"": ""leftJoy"",
                    ""type"": ""Value"",
                    ""id"": ""7234f501-1f21-466d-8f1c-b44d38d99fcd"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""StickDeadzone"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""rightJoy"",
                    ""type"": ""Value"",
                    ""id"": ""3518dbae-2f15-4a5a-b590-2aab1bddf073"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""StickDeadzone"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""buttonEast"",
                    ""type"": ""Button"",
                    ""id"": ""bdc69f32-fe22-4ec3-a160-cc69355646d4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""buttonWest"",
                    ""type"": ""Button"",
                    ""id"": ""f5303fbc-c305-40d6-abe6-08e804f78123"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""buttonNorth"",
                    ""type"": ""Button"",
                    ""id"": ""6d6ac9a7-98db-47fe-b401-27fb93ef6782"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""buttonSouth"",
                    ""type"": ""Button"",
                    ""id"": ""f2d452ea-d044-4454-b6d8-ab07ab5ea008"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""dpadEast"",
                    ""type"": ""Button"",
                    ""id"": ""4003e283-b131-4d35-a4d3-c8ba0f036159"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""dpadWest"",
                    ""type"": ""Button"",
                    ""id"": ""d23cacb8-0220-4177-b53a-2ae820af60b8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""dpadNorth"",
                    ""type"": ""Button"",
                    ""id"": ""6bb4788b-db16-447e-b6c4-f2a1924a9566"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""dpadSouth"",
                    ""type"": ""Button"",
                    ""id"": ""8e3bfdc7-44f2-4e5c-a393-255e0168706a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""start"",
                    ""type"": ""Button"",
                    ""id"": ""031bfc97-93d8-4937-acd7-911b77c012c5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""select"",
                    ""type"": ""Button"",
                    ""id"": ""f0fd069d-e2c6-4832-b935-e458ba7711d1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""shoulderWest"",
                    ""type"": ""Button"",
                    ""id"": ""303f47dc-19af-4d82-8470-6c3985f9d3ad"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""shoulderEast"",
                    ""type"": ""Button"",
                    ""id"": ""d2a2a12c-718e-443e-af6d-749c4d926701"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""triggerEast"",
                    ""type"": ""Value"",
                    ""id"": ""17b8509c-d5b0-49b7-b880-6c7036064840"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""triggerWest"",
                    ""type"": ""Value"",
                    ""id"": ""b59e049b-c67b-4427-8123-a7b2ed3f0ae3"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""joystickEastButton"",
                    ""type"": ""Button"",
                    ""id"": ""cdff8ce5-43fb-4b3f-b8d6-7d88b26334ab"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""fe38a6ed-b9a6-4ff4-a8d4-6317f2c35cc6"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": """",
                    ""action"": ""leftJoy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""22a68926-5f23-443c-8fb6-22e8328ae7e5"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": """",
                    ""action"": ""rightJoy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b6e2d035-43a4-402c-b22e-8b3add0e8e39"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""buttonEast"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f49c0a2f-6f0f-4fa6-b7a7-b0de9d7420b6"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""buttonWest"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4a8a6e1f-b78b-49f4-8585-8c2c93f86a18"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""buttonNorth"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5dc7367a-acb9-424e-8373-18c93ec9d91e"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""buttonSouth"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""75579814-b70b-4bd6-a917-65c13a3a285c"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""dpadEast"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f64a2dde-25e9-4c64-9618-517328ea5a63"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""dpadWest"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f05b85bc-afc6-4578-937b-7c5ab9af77d5"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""dpadNorth"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2eafde30-b418-4297-b253-7b0c4aeb8c42"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""dpadSouth"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d3e8f8a4-4e48-4439-9b1b-8e1254550459"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""shoulderWest"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8a0881f3-a6c6-41d8-abcf-10ad4d4cb355"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""shoulderEast"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""995bece6-c93a-4d8e-8feb-00d91759fd1d"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""triggerEast"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3a7988ed-0d76-4510-b512-dac5ab4f469e"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""triggerWest"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6f7dd8ea-cdba-4753-b1d7-1dec4e0d0d5e"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9f63068e-473e-4246-8533-e9928da2877c"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9f14f65f-01b3-481a-b89a-caa1264c6f22"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""joystickEastButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""BoardControl"",
            ""id"": ""b7c0da5e-d23c-496a-aa31-8bc5a687cd54"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""4e5c7c35-7ace-4164-9ed6-9a39954d6e45"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9700d414-287f-416b-8e9e-b1953855a10c"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""KeyboardControl"",
            ""id"": ""5be4993b-5144-45bd-ab0b-184046fd6643"",
            ""actions"": [
                {
                    ""name"": ""onekey"",
                    ""type"": ""Button"",
                    ""id"": ""73f06b34-76ce-47db-8342-b07e0224a1bd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""twokey"",
                    ""type"": ""Button"",
                    ""id"": ""c8f6ce3f-645d-4435-b776-a3a7b3b51879"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""threekey"",
                    ""type"": ""Button"",
                    ""id"": ""344f5111-ec11-4477-a081-afbe0b2e5932"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""fourkey"",
                    ""type"": ""Button"",
                    ""id"": ""ca827380-0198-4304-82da-be89bc095084"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""fivekey"",
                    ""type"": ""Button"",
                    ""id"": ""f3d9792c-ac2f-493b-b612-7255a8d7ec55"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""sixkey"",
                    ""type"": ""Button"",
                    ""id"": ""021d83d6-da0a-4170-a16a-57a46f59891e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""sevenkey"",
                    ""type"": ""Button"",
                    ""id"": ""a78b63f6-9dfb-4a5e-9452-23fa67b24867"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""eightkey"",
                    ""type"": ""Button"",
                    ""id"": ""ddb43dd6-7291-4fde-b6ed-7ab901dc7290"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ninekey"",
                    ""type"": ""Button"",
                    ""id"": ""55db3e19-ebab-47f7-bbd3-ab4c51ff52b0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""zerokey"",
                    ""type"": ""Button"",
                    ""id"": ""d2e6e20d-8a6e-44c8-92cd-c821d5472474"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Enter"",
                    ""type"": ""Button"",
                    ""id"": ""9a878c63-d281-472f-89f8-8e54758913a5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""spacekey"",
                    ""type"": ""Button"",
                    ""id"": ""2bb3a272-254d-40a7-8076-86b6b81e2a30"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""backspacekey"",
                    ""type"": ""Button"",
                    ""id"": ""af88aed1-dc94-43f9-908b-be864de67d5b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""shiftkey"",
                    ""type"": ""Button"",
                    ""id"": ""4aa27a3e-72d7-4ee0-8b16-8f2498e29eae"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""69743324-2ef1-4c77-93eb-7d2f2004f0e6"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""onekey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f194297a-9f0f-44e0-8c3f-ac6c2785bbd4"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""twokey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""75e9d925-4aed-4181-89c7-e3f776feaa88"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""threekey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aedaa558-fdd1-45f3-8e6f-cd8a9830e5de"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""fourkey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7f9a993a-b200-44b6-a181-4915799dde07"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""fivekey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5ec3fd84-fb53-44fd-b401-bf57d638be76"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""sixkey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""563f3207-9e0f-444d-8379-c1794410ae77"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""sevenkey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2439bef1-38d1-4950-a475-0a4b69446adc"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""eightkey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c0f92fc8-e116-47ff-8a97-e125c9b80175"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ninekey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f7161b7a-7110-47e5-93e2-79c934b0270a"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""zerokey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2cb5fd6d-b042-495c-b4c4-dfb521971cdd"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Enter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e4f07303-3c56-41bc-9d7a-e6e6053802ab"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""spacekey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fd46bb74-6c8f-43b1-bcc4-28b70a65fb55"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""backspacekey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8139c5f6-a6e0-4d93-b4b2-a9dfbc1d835c"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""shiftkey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // DriveControl
        m_DriveControl = asset.FindActionMap("DriveControl", throwIfNotFound: true);
        m_DriveControl_leftJoy = m_DriveControl.FindAction("leftJoy", throwIfNotFound: true);
        m_DriveControl_rightJoy = m_DriveControl.FindAction("rightJoy", throwIfNotFound: true);
        m_DriveControl_buttonEast = m_DriveControl.FindAction("buttonEast", throwIfNotFound: true);
        m_DriveControl_buttonWest = m_DriveControl.FindAction("buttonWest", throwIfNotFound: true);
        m_DriveControl_buttonNorth = m_DriveControl.FindAction("buttonNorth", throwIfNotFound: true);
        m_DriveControl_buttonSouth = m_DriveControl.FindAction("buttonSouth", throwIfNotFound: true);
        m_DriveControl_dpadEast = m_DriveControl.FindAction("dpadEast", throwIfNotFound: true);
        m_DriveControl_dpadWest = m_DriveControl.FindAction("dpadWest", throwIfNotFound: true);
        m_DriveControl_dpadNorth = m_DriveControl.FindAction("dpadNorth", throwIfNotFound: true);
        m_DriveControl_dpadSouth = m_DriveControl.FindAction("dpadSouth", throwIfNotFound: true);
        m_DriveControl_start = m_DriveControl.FindAction("start", throwIfNotFound: true);
        m_DriveControl_select = m_DriveControl.FindAction("select", throwIfNotFound: true);
        m_DriveControl_shoulderWest = m_DriveControl.FindAction("shoulderWest", throwIfNotFound: true);
        m_DriveControl_shoulderEast = m_DriveControl.FindAction("shoulderEast", throwIfNotFound: true);
        m_DriveControl_triggerEast = m_DriveControl.FindAction("triggerEast", throwIfNotFound: true);
        m_DriveControl_triggerWest = m_DriveControl.FindAction("triggerWest", throwIfNotFound: true);
        m_DriveControl_joystickEastButton = m_DriveControl.FindAction("joystickEastButton", throwIfNotFound: true);
        // BoardControl
        m_BoardControl = asset.FindActionMap("BoardControl", throwIfNotFound: true);
        m_BoardControl_Newaction = m_BoardControl.FindAction("New action", throwIfNotFound: true);
        // KeyboardControl
        m_KeyboardControl = asset.FindActionMap("KeyboardControl", throwIfNotFound: true);
        m_KeyboardControl_onekey = m_KeyboardControl.FindAction("onekey", throwIfNotFound: true);
        m_KeyboardControl_twokey = m_KeyboardControl.FindAction("twokey", throwIfNotFound: true);
        m_KeyboardControl_threekey = m_KeyboardControl.FindAction("threekey", throwIfNotFound: true);
        m_KeyboardControl_fourkey = m_KeyboardControl.FindAction("fourkey", throwIfNotFound: true);
        m_KeyboardControl_fivekey = m_KeyboardControl.FindAction("fivekey", throwIfNotFound: true);
        m_KeyboardControl_sixkey = m_KeyboardControl.FindAction("sixkey", throwIfNotFound: true);
        m_KeyboardControl_sevenkey = m_KeyboardControl.FindAction("sevenkey", throwIfNotFound: true);
        m_KeyboardControl_eightkey = m_KeyboardControl.FindAction("eightkey", throwIfNotFound: true);
        m_KeyboardControl_ninekey = m_KeyboardControl.FindAction("ninekey", throwIfNotFound: true);
        m_KeyboardControl_zerokey = m_KeyboardControl.FindAction("zerokey", throwIfNotFound: true);
        m_KeyboardControl_Enter = m_KeyboardControl.FindAction("Enter", throwIfNotFound: true);
        m_KeyboardControl_spacekey = m_KeyboardControl.FindAction("spacekey", throwIfNotFound: true);
        m_KeyboardControl_backspacekey = m_KeyboardControl.FindAction("backspacekey", throwIfNotFound: true);
        m_KeyboardControl_shiftkey = m_KeyboardControl.FindAction("shiftkey", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // DriveControl
    private readonly InputActionMap m_DriveControl;
    private List<IDriveControlActions> m_DriveControlActionsCallbackInterfaces = new List<IDriveControlActions>();
    private readonly InputAction m_DriveControl_leftJoy;
    private readonly InputAction m_DriveControl_rightJoy;
    private readonly InputAction m_DriveControl_buttonEast;
    private readonly InputAction m_DriveControl_buttonWest;
    private readonly InputAction m_DriveControl_buttonNorth;
    private readonly InputAction m_DriveControl_buttonSouth;
    private readonly InputAction m_DriveControl_dpadEast;
    private readonly InputAction m_DriveControl_dpadWest;
    private readonly InputAction m_DriveControl_dpadNorth;
    private readonly InputAction m_DriveControl_dpadSouth;
    private readonly InputAction m_DriveControl_start;
    private readonly InputAction m_DriveControl_select;
    private readonly InputAction m_DriveControl_shoulderWest;
    private readonly InputAction m_DriveControl_shoulderEast;
    private readonly InputAction m_DriveControl_triggerEast;
    private readonly InputAction m_DriveControl_triggerWest;
    private readonly InputAction m_DriveControl_joystickEastButton;
    public struct DriveControlActions
    {
        private @GameController m_Wrapper;
        public DriveControlActions(@GameController wrapper) { m_Wrapper = wrapper; }
        public InputAction @leftJoy => m_Wrapper.m_DriveControl_leftJoy;
        public InputAction @rightJoy => m_Wrapper.m_DriveControl_rightJoy;
        public InputAction @buttonEast => m_Wrapper.m_DriveControl_buttonEast;
        public InputAction @buttonWest => m_Wrapper.m_DriveControl_buttonWest;
        public InputAction @buttonNorth => m_Wrapper.m_DriveControl_buttonNorth;
        public InputAction @buttonSouth => m_Wrapper.m_DriveControl_buttonSouth;
        public InputAction @dpadEast => m_Wrapper.m_DriveControl_dpadEast;
        public InputAction @dpadWest => m_Wrapper.m_DriveControl_dpadWest;
        public InputAction @dpadNorth => m_Wrapper.m_DriveControl_dpadNorth;
        public InputAction @dpadSouth => m_Wrapper.m_DriveControl_dpadSouth;
        public InputAction @start => m_Wrapper.m_DriveControl_start;
        public InputAction @select => m_Wrapper.m_DriveControl_select;
        public InputAction @shoulderWest => m_Wrapper.m_DriveControl_shoulderWest;
        public InputAction @shoulderEast => m_Wrapper.m_DriveControl_shoulderEast;
        public InputAction @triggerEast => m_Wrapper.m_DriveControl_triggerEast;
        public InputAction @triggerWest => m_Wrapper.m_DriveControl_triggerWest;
        public InputAction @joystickEastButton => m_Wrapper.m_DriveControl_joystickEastButton;
        public InputActionMap Get() { return m_Wrapper.m_DriveControl; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DriveControlActions set) { return set.Get(); }
        public void AddCallbacks(IDriveControlActions instance)
        {
            if (instance == null || m_Wrapper.m_DriveControlActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DriveControlActionsCallbackInterfaces.Add(instance);
            @leftJoy.started += instance.OnLeftJoy;
            @leftJoy.performed += instance.OnLeftJoy;
            @leftJoy.canceled += instance.OnLeftJoy;
            @rightJoy.started += instance.OnRightJoy;
            @rightJoy.performed += instance.OnRightJoy;
            @rightJoy.canceled += instance.OnRightJoy;
            @buttonEast.started += instance.OnButtonEast;
            @buttonEast.performed += instance.OnButtonEast;
            @buttonEast.canceled += instance.OnButtonEast;
            @buttonWest.started += instance.OnButtonWest;
            @buttonWest.performed += instance.OnButtonWest;
            @buttonWest.canceled += instance.OnButtonWest;
            @buttonNorth.started += instance.OnButtonNorth;
            @buttonNorth.performed += instance.OnButtonNorth;
            @buttonNorth.canceled += instance.OnButtonNorth;
            @buttonSouth.started += instance.OnButtonSouth;
            @buttonSouth.performed += instance.OnButtonSouth;
            @buttonSouth.canceled += instance.OnButtonSouth;
            @dpadEast.started += instance.OnDpadEast;
            @dpadEast.performed += instance.OnDpadEast;
            @dpadEast.canceled += instance.OnDpadEast;
            @dpadWest.started += instance.OnDpadWest;
            @dpadWest.performed += instance.OnDpadWest;
            @dpadWest.canceled += instance.OnDpadWest;
            @dpadNorth.started += instance.OnDpadNorth;
            @dpadNorth.performed += instance.OnDpadNorth;
            @dpadNorth.canceled += instance.OnDpadNorth;
            @dpadSouth.started += instance.OnDpadSouth;
            @dpadSouth.performed += instance.OnDpadSouth;
            @dpadSouth.canceled += instance.OnDpadSouth;
            @start.started += instance.OnStart;
            @start.performed += instance.OnStart;
            @start.canceled += instance.OnStart;
            @select.started += instance.OnSelect;
            @select.performed += instance.OnSelect;
            @select.canceled += instance.OnSelect;
            @shoulderWest.started += instance.OnShoulderWest;
            @shoulderWest.performed += instance.OnShoulderWest;
            @shoulderWest.canceled += instance.OnShoulderWest;
            @shoulderEast.started += instance.OnShoulderEast;
            @shoulderEast.performed += instance.OnShoulderEast;
            @shoulderEast.canceled += instance.OnShoulderEast;
            @triggerEast.started += instance.OnTriggerEast;
            @triggerEast.performed += instance.OnTriggerEast;
            @triggerEast.canceled += instance.OnTriggerEast;
            @triggerWest.started += instance.OnTriggerWest;
            @triggerWest.performed += instance.OnTriggerWest;
            @triggerWest.canceled += instance.OnTriggerWest;
            @joystickEastButton.started += instance.OnJoystickEastButton;
            @joystickEastButton.performed += instance.OnJoystickEastButton;
            @joystickEastButton.canceled += instance.OnJoystickEastButton;
        }

        private void UnregisterCallbacks(IDriveControlActions instance)
        {
            @leftJoy.started -= instance.OnLeftJoy;
            @leftJoy.performed -= instance.OnLeftJoy;
            @leftJoy.canceled -= instance.OnLeftJoy;
            @rightJoy.started -= instance.OnRightJoy;
            @rightJoy.performed -= instance.OnRightJoy;
            @rightJoy.canceled -= instance.OnRightJoy;
            @buttonEast.started -= instance.OnButtonEast;
            @buttonEast.performed -= instance.OnButtonEast;
            @buttonEast.canceled -= instance.OnButtonEast;
            @buttonWest.started -= instance.OnButtonWest;
            @buttonWest.performed -= instance.OnButtonWest;
            @buttonWest.canceled -= instance.OnButtonWest;
            @buttonNorth.started -= instance.OnButtonNorth;
            @buttonNorth.performed -= instance.OnButtonNorth;
            @buttonNorth.canceled -= instance.OnButtonNorth;
            @buttonSouth.started -= instance.OnButtonSouth;
            @buttonSouth.performed -= instance.OnButtonSouth;
            @buttonSouth.canceled -= instance.OnButtonSouth;
            @dpadEast.started -= instance.OnDpadEast;
            @dpadEast.performed -= instance.OnDpadEast;
            @dpadEast.canceled -= instance.OnDpadEast;
            @dpadWest.started -= instance.OnDpadWest;
            @dpadWest.performed -= instance.OnDpadWest;
            @dpadWest.canceled -= instance.OnDpadWest;
            @dpadNorth.started -= instance.OnDpadNorth;
            @dpadNorth.performed -= instance.OnDpadNorth;
            @dpadNorth.canceled -= instance.OnDpadNorth;
            @dpadSouth.started -= instance.OnDpadSouth;
            @dpadSouth.performed -= instance.OnDpadSouth;
            @dpadSouth.canceled -= instance.OnDpadSouth;
            @start.started -= instance.OnStart;
            @start.performed -= instance.OnStart;
            @start.canceled -= instance.OnStart;
            @select.started -= instance.OnSelect;
            @select.performed -= instance.OnSelect;
            @select.canceled -= instance.OnSelect;
            @shoulderWest.started -= instance.OnShoulderWest;
            @shoulderWest.performed -= instance.OnShoulderWest;
            @shoulderWest.canceled -= instance.OnShoulderWest;
            @shoulderEast.started -= instance.OnShoulderEast;
            @shoulderEast.performed -= instance.OnShoulderEast;
            @shoulderEast.canceled -= instance.OnShoulderEast;
            @triggerEast.started -= instance.OnTriggerEast;
            @triggerEast.performed -= instance.OnTriggerEast;
            @triggerEast.canceled -= instance.OnTriggerEast;
            @triggerWest.started -= instance.OnTriggerWest;
            @triggerWest.performed -= instance.OnTriggerWest;
            @triggerWest.canceled -= instance.OnTriggerWest;
            @joystickEastButton.started -= instance.OnJoystickEastButton;
            @joystickEastButton.performed -= instance.OnJoystickEastButton;
            @joystickEastButton.canceled -= instance.OnJoystickEastButton;
        }

        public void RemoveCallbacks(IDriveControlActions instance)
        {
            if (m_Wrapper.m_DriveControlActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDriveControlActions instance)
        {
            foreach (var item in m_Wrapper.m_DriveControlActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DriveControlActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DriveControlActions @DriveControl => new DriveControlActions(this);

    // BoardControl
    private readonly InputActionMap m_BoardControl;
    private List<IBoardControlActions> m_BoardControlActionsCallbackInterfaces = new List<IBoardControlActions>();
    private readonly InputAction m_BoardControl_Newaction;
    public struct BoardControlActions
    {
        private @GameController m_Wrapper;
        public BoardControlActions(@GameController wrapper) { m_Wrapper = wrapper; }
        public InputAction @Newaction => m_Wrapper.m_BoardControl_Newaction;
        public InputActionMap Get() { return m_Wrapper.m_BoardControl; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BoardControlActions set) { return set.Get(); }
        public void AddCallbacks(IBoardControlActions instance)
        {
            if (instance == null || m_Wrapper.m_BoardControlActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_BoardControlActionsCallbackInterfaces.Add(instance);
            @Newaction.started += instance.OnNewaction;
            @Newaction.performed += instance.OnNewaction;
            @Newaction.canceled += instance.OnNewaction;
        }

        private void UnregisterCallbacks(IBoardControlActions instance)
        {
            @Newaction.started -= instance.OnNewaction;
            @Newaction.performed -= instance.OnNewaction;
            @Newaction.canceled -= instance.OnNewaction;
        }

        public void RemoveCallbacks(IBoardControlActions instance)
        {
            if (m_Wrapper.m_BoardControlActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IBoardControlActions instance)
        {
            foreach (var item in m_Wrapper.m_BoardControlActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_BoardControlActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public BoardControlActions @BoardControl => new BoardControlActions(this);

    // KeyboardControl
    private readonly InputActionMap m_KeyboardControl;
    private List<IKeyboardControlActions> m_KeyboardControlActionsCallbackInterfaces = new List<IKeyboardControlActions>();
    private readonly InputAction m_KeyboardControl_onekey;
    private readonly InputAction m_KeyboardControl_twokey;
    private readonly InputAction m_KeyboardControl_threekey;
    private readonly InputAction m_KeyboardControl_fourkey;
    private readonly InputAction m_KeyboardControl_fivekey;
    private readonly InputAction m_KeyboardControl_sixkey;
    private readonly InputAction m_KeyboardControl_sevenkey;
    private readonly InputAction m_KeyboardControl_eightkey;
    private readonly InputAction m_KeyboardControl_ninekey;
    private readonly InputAction m_KeyboardControl_zerokey;
    private readonly InputAction m_KeyboardControl_Enter;
    private readonly InputAction m_KeyboardControl_spacekey;
    private readonly InputAction m_KeyboardControl_backspacekey;
    private readonly InputAction m_KeyboardControl_shiftkey;
    public struct KeyboardControlActions
    {
        private @GameController m_Wrapper;
        public KeyboardControlActions(@GameController wrapper) { m_Wrapper = wrapper; }
        public InputAction @onekey => m_Wrapper.m_KeyboardControl_onekey;
        public InputAction @twokey => m_Wrapper.m_KeyboardControl_twokey;
        public InputAction @threekey => m_Wrapper.m_KeyboardControl_threekey;
        public InputAction @fourkey => m_Wrapper.m_KeyboardControl_fourkey;
        public InputAction @fivekey => m_Wrapper.m_KeyboardControl_fivekey;
        public InputAction @sixkey => m_Wrapper.m_KeyboardControl_sixkey;
        public InputAction @sevenkey => m_Wrapper.m_KeyboardControl_sevenkey;
        public InputAction @eightkey => m_Wrapper.m_KeyboardControl_eightkey;
        public InputAction @ninekey => m_Wrapper.m_KeyboardControl_ninekey;
        public InputAction @zerokey => m_Wrapper.m_KeyboardControl_zerokey;
        public InputAction @Enter => m_Wrapper.m_KeyboardControl_Enter;
        public InputAction @spacekey => m_Wrapper.m_KeyboardControl_spacekey;
        public InputAction @backspacekey => m_Wrapper.m_KeyboardControl_backspacekey;
        public InputAction @shiftkey => m_Wrapper.m_KeyboardControl_shiftkey;
        public InputActionMap Get() { return m_Wrapper.m_KeyboardControl; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(KeyboardControlActions set) { return set.Get(); }
        public void AddCallbacks(IKeyboardControlActions instance)
        {
            if (instance == null || m_Wrapper.m_KeyboardControlActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_KeyboardControlActionsCallbackInterfaces.Add(instance);
            @onekey.started += instance.OnOnekey;
            @onekey.performed += instance.OnOnekey;
            @onekey.canceled += instance.OnOnekey;
            @twokey.started += instance.OnTwokey;
            @twokey.performed += instance.OnTwokey;
            @twokey.canceled += instance.OnTwokey;
            @threekey.started += instance.OnThreekey;
            @threekey.performed += instance.OnThreekey;
            @threekey.canceled += instance.OnThreekey;
            @fourkey.started += instance.OnFourkey;
            @fourkey.performed += instance.OnFourkey;
            @fourkey.canceled += instance.OnFourkey;
            @fivekey.started += instance.OnFivekey;
            @fivekey.performed += instance.OnFivekey;
            @fivekey.canceled += instance.OnFivekey;
            @sixkey.started += instance.OnSixkey;
            @sixkey.performed += instance.OnSixkey;
            @sixkey.canceled += instance.OnSixkey;
            @sevenkey.started += instance.OnSevenkey;
            @sevenkey.performed += instance.OnSevenkey;
            @sevenkey.canceled += instance.OnSevenkey;
            @eightkey.started += instance.OnEightkey;
            @eightkey.performed += instance.OnEightkey;
            @eightkey.canceled += instance.OnEightkey;
            @ninekey.started += instance.OnNinekey;
            @ninekey.performed += instance.OnNinekey;
            @ninekey.canceled += instance.OnNinekey;
            @zerokey.started += instance.OnZerokey;
            @zerokey.performed += instance.OnZerokey;
            @zerokey.canceled += instance.OnZerokey;
            @Enter.started += instance.OnEnter;
            @Enter.performed += instance.OnEnter;
            @Enter.canceled += instance.OnEnter;
            @spacekey.started += instance.OnSpacekey;
            @spacekey.performed += instance.OnSpacekey;
            @spacekey.canceled += instance.OnSpacekey;
            @backspacekey.started += instance.OnBackspacekey;
            @backspacekey.performed += instance.OnBackspacekey;
            @backspacekey.canceled += instance.OnBackspacekey;
            @shiftkey.started += instance.OnShiftkey;
            @shiftkey.performed += instance.OnShiftkey;
            @shiftkey.canceled += instance.OnShiftkey;
        }

        private void UnregisterCallbacks(IKeyboardControlActions instance)
        {
            @onekey.started -= instance.OnOnekey;
            @onekey.performed -= instance.OnOnekey;
            @onekey.canceled -= instance.OnOnekey;
            @twokey.started -= instance.OnTwokey;
            @twokey.performed -= instance.OnTwokey;
            @twokey.canceled -= instance.OnTwokey;
            @threekey.started -= instance.OnThreekey;
            @threekey.performed -= instance.OnThreekey;
            @threekey.canceled -= instance.OnThreekey;
            @fourkey.started -= instance.OnFourkey;
            @fourkey.performed -= instance.OnFourkey;
            @fourkey.canceled -= instance.OnFourkey;
            @fivekey.started -= instance.OnFivekey;
            @fivekey.performed -= instance.OnFivekey;
            @fivekey.canceled -= instance.OnFivekey;
            @sixkey.started -= instance.OnSixkey;
            @sixkey.performed -= instance.OnSixkey;
            @sixkey.canceled -= instance.OnSixkey;
            @sevenkey.started -= instance.OnSevenkey;
            @sevenkey.performed -= instance.OnSevenkey;
            @sevenkey.canceled -= instance.OnSevenkey;
            @eightkey.started -= instance.OnEightkey;
            @eightkey.performed -= instance.OnEightkey;
            @eightkey.canceled -= instance.OnEightkey;
            @ninekey.started -= instance.OnNinekey;
            @ninekey.performed -= instance.OnNinekey;
            @ninekey.canceled -= instance.OnNinekey;
            @zerokey.started -= instance.OnZerokey;
            @zerokey.performed -= instance.OnZerokey;
            @zerokey.canceled -= instance.OnZerokey;
            @Enter.started -= instance.OnEnter;
            @Enter.performed -= instance.OnEnter;
            @Enter.canceled -= instance.OnEnter;
            @spacekey.started -= instance.OnSpacekey;
            @spacekey.performed -= instance.OnSpacekey;
            @spacekey.canceled -= instance.OnSpacekey;
            @backspacekey.started -= instance.OnBackspacekey;
            @backspacekey.performed -= instance.OnBackspacekey;
            @backspacekey.canceled -= instance.OnBackspacekey;
            @shiftkey.started -= instance.OnShiftkey;
            @shiftkey.performed -= instance.OnShiftkey;
            @shiftkey.canceled -= instance.OnShiftkey;
        }

        public void RemoveCallbacks(IKeyboardControlActions instance)
        {
            if (m_Wrapper.m_KeyboardControlActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IKeyboardControlActions instance)
        {
            foreach (var item in m_Wrapper.m_KeyboardControlActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_KeyboardControlActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public KeyboardControlActions @KeyboardControl => new KeyboardControlActions(this);
    public interface IDriveControlActions
    {
        void OnLeftJoy(InputAction.CallbackContext context);
        void OnRightJoy(InputAction.CallbackContext context);
        void OnButtonEast(InputAction.CallbackContext context);
        void OnButtonWest(InputAction.CallbackContext context);
        void OnButtonNorth(InputAction.CallbackContext context);
        void OnButtonSouth(InputAction.CallbackContext context);
        void OnDpadEast(InputAction.CallbackContext context);
        void OnDpadWest(InputAction.CallbackContext context);
        void OnDpadNorth(InputAction.CallbackContext context);
        void OnDpadSouth(InputAction.CallbackContext context);
        void OnStart(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
        void OnShoulderWest(InputAction.CallbackContext context);
        void OnShoulderEast(InputAction.CallbackContext context);
        void OnTriggerEast(InputAction.CallbackContext context);
        void OnTriggerWest(InputAction.CallbackContext context);
        void OnJoystickEastButton(InputAction.CallbackContext context);
    }
    public interface IBoardControlActions
    {
        void OnNewaction(InputAction.CallbackContext context);
    }
    public interface IKeyboardControlActions
    {
        void OnOnekey(InputAction.CallbackContext context);
        void OnTwokey(InputAction.CallbackContext context);
        void OnThreekey(InputAction.CallbackContext context);
        void OnFourkey(InputAction.CallbackContext context);
        void OnFivekey(InputAction.CallbackContext context);
        void OnSixkey(InputAction.CallbackContext context);
        void OnSevenkey(InputAction.CallbackContext context);
        void OnEightkey(InputAction.CallbackContext context);
        void OnNinekey(InputAction.CallbackContext context);
        void OnZerokey(InputAction.CallbackContext context);
        void OnEnter(InputAction.CallbackContext context);
        void OnSpacekey(InputAction.CallbackContext context);
        void OnBackspacekey(InputAction.CallbackContext context);
        void OnShiftkey(InputAction.CallbackContext context);
    }
}
